### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [joewhale/splurty-app#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by joewhale** [comment]
Billy,

I'm not sure I got it. I'm working on my nomster app as well, so I added the <meta name="viewport" content="width=device-width, initial-scale=1"> tag in my head tag in my application.html and there was no difference on mobile. Am I on the right track?

**Comment by joewhale** [comment]
nevermind! it is because `<meta name="viewport" content="width=device-width, initial-scale=1">` had the "initial-scale=1" which screws it up. Without it, it works just fine! :)

**Comment by BillyMassey** [comment]
Glad you got it figured out Joel! Way to go and keep up the awesome work!
-Billy
